### ISSUE TITLE
Work with ONL ?

### ISSUE THREAD

**Issue by bahirul** [microsonic/usonic#25]
Hi,

Can i use this for work with ONL, i have as7512-32x with cavium, buat sonic image seem can't be installed, the latest build sonic for my device is 2017 release and not work, the only working os is ONL. But i don't know about asic / switch configuration because ONL is only base OS.

Thanks

**Comment by ishidawataru** [comment]
Sorry for the delay. If you have a compatible libsai.so, it should work.
